### ISSUE TITLE
finish tables

### ISSUE THREAD

**Issue by denten** [JonathanReeve/vim-article#3]
Please go through and complete the tables. Remember, we are not going to completeness. And we should probably target prose rather than code-oriented idioms. Skip things like "move to the next bracket" which are rarely used in prose writing.

**Comment by JonathanReeve** [comment]
Fixed in 48c2818c71e4cc0088dad6119256ebbca268ed6e...0eb4543d350b015dba31f1686905e5ece303e277. I tried to keep it minimaḷ--informative but simple.
